# /root/.bashrc
# Bash configuration; aliases, functions, and options.
# Executed by root non-login shells.

if [ -r /etc/bashrc ]; then
    source /etc/bashrc
fi

# Wayland as of F25 doesn't source the profile script, so:
# (https://bugzilla.gnome.org/show_bug.cgi?id=736660)
if [ -r ~/.profile ]; then
    source ~/.profile
fi

# Set LS_COLORS to show appropriate colors for different file types.
eval "$(dircolors --sh)"

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ls='LC_COLLATE=C ls --color=auto --human-readable --group-directories-first --quoting-style=literal'
alias ll='ls -la'
alias grep='grep --color=auto'
alias e='$EDITOR'

# Write throwaway bash code, and evaluate it.
function ebash() {
    local SCRIPT=~/.local/share/ebash.bash
    $EDITOR "$SCRIPT"
    cat "$SCRIPT"
    echo '----------'
    source "$SCRIPT"
}

# Correct minor errors when spelling directories for `cd`.
shopt -s cdspell

# Update $LINES and $COLUMNS after every command.
shopt -s checkwinsize

# Save multiple-line commands in the same history entry.
shopt -s cmdhist

# Correct minor errors when spelling directories.
shopt -s dirspell

# Enable operators like ?, *, + to work on pattern lists.
shopt -s extglob

# Allow use of ** for recursive pathname expansion.
shopt -s globstar

# Append to history file on exit rather than overwriting it.
shopt -s histappend

# Use case-insensitive pathname expansion.
shopt -s nocaseglob

